baseURL = 'https://onlife.ninja/'
languageCode = 'en-us'
title = 'onlife.ninja'
theme = "nightfall"

[params]
user = "xqus"
hostname = "onlife.ninja"
#footerHtml = 'CC-0, Built with <a href="https://gohugo.io" class="footerLink">Hugo</a> and <a href="https://github.com/LordMathis/hugo-theme-nightfall" class="footerLink">Nightfall</a> theme'
sitedescription = 'Your website description'

  [params.author]
    name = "xqus"
    email = "larsen@xqus.com"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"